# Spring Properties
spring:
  application:
    name: web-service
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory Template location for this application only
    suffix: .html
    check-template-location: true
    mode: HTML
    encoding: UTF-8
    content-type: text/html

# Map the error path to error template (for Thymeleaf)
error.path: /error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/    # http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

# Enable actuator access without security checks - DEVELOPEMENT ONLY
# Spring Boot 1.5
# management.security.enabled: false
# Spring Boot 2.x
management.endpoints.web.exposure.include: '*'